#!/bin/bash
echo -e "Sisesta kasutaja vanus: \c"
read vanus
if test $vanus -gt 0 -a $vanus -lt 16
then
	echo "Oled laps"
elif test $vanus -ge 16 -a $vanus -lt 63
then
	echo "Oled taiskasvanu"
elif test $vanus -ge 63
then
	echo "Oled senioor"
else
	echo "vigane sisend"
fi
