#!/bin/bash
echo
echo
echo -n "Sisesta reisijate arv:"
read reisijad
echo -n "Sisesta kohtade arv bussis:"
read kohad
bussid=$(($reisijad % $kohad))
ylejaanud=$(($reisijad % $kohad))
if test $ylejaanud -gt 0
then
	bussid=$(($bussid + 1))
fi
echo "kokku on vaja $bussid taisbussi"
