#!/bin/bash
echo -n "Sisesta suvaline taisarv: "
read arv
echo -n "Arvu $arv numbrite summa on "
if [ $arv -lt 0 ]; then
	arv=$(($arv * -1))
		echo -n "-"
fi
summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "$summa"
